Use case dbst
edgefarm/ads-tenant-demo pull request #2
Opened 2021-06-29 07:50 UTC by KlausPopp

Changed benthos config to support in addition use-case-dbst.
Added grafana dashboard for seat-info-monitoring

2021-06-29 14:41 UTC, KairaMiu requested changes

2021-06-29 14:41 UTC, KairaMiu commented on deploy.sh
> +curl -L https://raw.githubusercontent.com/edgefarm/edgefarm-demos/add-trainsystem-monitor/train-simulation/schemas/system_event.avsc -o schemas/system_event.avsc
Please switch to main branch

2021-06-29 19:09 UTC, KlausPopp commented on deploy.sh
> +curl -L https://raw.githubusercontent.com/edgefarm/edgefarm-demos/add-trainsystem-monitor/train-simulation/schemas/system_event.avsc -o schemas/system_event.avsc
Done

2021-06-30 05:40 UTC, KairaMiu approved these changes

2021-06-30 06:32 UTC, merged